---
title: "Final code with more full exploration of data and errors"
author: "JasonL"
date: "2023-02-06"
output: 
  html_document: 
    keep_md: yes
---

SECTION 1: Upload packages

```{r Packages, message=FALSE, warning=FALSE}
library(lme4) # mixed effects models
library(lmerTest) # get results of lmer models
library(reshape2) # melting dataframes
library(plyr) # manipulating data frames
library(dplyr) # manipulating data frames
library(ggplot2) # plotting
library(cowplot) # luxury plotting
library(grid) # arranging and labelling plots
library(gridExtra)
library(emmeans) # allows extraction of bacteria-specific regression estimates.
```

SECTION 2: Upload data for 2020 and 2019 experiments.

```{r data, message=FALSE, warning=FALSE}
setwd("C:/Users/jason/Dropbox/My PC (DESKTOP-IOO274E)/Desktop/Data/Lemna_singleinoculations/Lemna_single_inoculations")

df.CW<-read.table('CW_mixed_inoculation_data.txt', header=F, na.strings="", sep="\t")
names(df.CW)<-c('pop','plt','bac','id','frd0','pix0','per0','grn0','grnper0','frd1','pix1','per1','grn1','grnper1','abs')

#Fix the structure for bacterial inoculation and plant
df.CW$bac <- factor(df.CW$bac, levels = c("Control", "1", "2", "3", "4", "5","6","7","8","9","10","All10"))
df.CW$plt <- as.factor(df.CW$plt)

# Add in edge effects. So for each 24 well plate, all but 6,7,10,11,14,15,18, and 19 are edge.
edge<-c(rep("Y",5), rep("N",2), rep("Y",2),rep("N",2), rep("Y",2), rep("N",2), rep("Y",2),rep("N",2), rep("Y",5))

#Final plate has 8 samples only
edge2<-rep(edge,38)
edge2<-c(edge2, rep("Y",5), rep("N",2), "Y")
df.CW$edge<-edge2

df.CW$edge <- as.factor(df.CW$edge)

plate<-vector()
# Create vector for plate - 38 full, 39th with 8 wells
for (i in 1:38){
  plate<-c(plate, rep(i,24))
}
plate<-c(plate,rep(39,8))

df.CW$plate <- plate
df.CW$plate <- as.factor(df.CW$plate)

#Take out errors (pipetting errors, wrong bacteria)
df.CW<-df.CW[-c(453,494,798),]

# Calculate growth.
df.CW$Grt<-df.CW$pix1 - df.CW$pix0

# Let's log abs count
df.CW$logabs<-log(df.CW$abs)

#Let's create separate dataframes for each population # Going to get the label 2020
df.C.2020<-subset(df.CW, df.CW$pop== "Churchill")
df.W.2020<-subset(df.CW, df.CW$pop== "Wellspring")

# Change factor order of bacteria to reflect their effects on duckweed growth.
#First, let's change the order of bacteria, ranked by effect. 
df.C.2020$bac<- factor(df.C.2020$bac, levels = c("Control","1","8","6","3","7","10","9","4","5","2","All10"))
# Assign names from sequencing
levels(df.C.2020$bac) <- c("Control","Flavobacterium \nsuccinicans 1","Bosea \nmassiliensis","Aeromonas \nsalmonicida","Ohtaekwangia \nkoreensis","Flavobacterium \nsuccinicans 2","Falsiroseomonas \nstagni","Parasediminibacterium \npaludis","Arcicella sp.","Microbacterium \noxydans","Pseudomonas \nprotogens","All 10 bacteria")

df.W.2020$bac<- factor(df.W.2020$bac, levels = c("Control","2","8","1","9","6","3","5","4","7","10","All10"))
levels(df.W.2020$bac) <- c("Control","Sphingomonas \npituitosa 1","Flaviflagellibacter \ndeserti","Rhizobium \nrosettiformans","Rhizorhabdus \nwittichii 1","Rhizobium \ncapsici 1","Pseudomonas \nprotogens","Rhizorhabdus \nwittichii 2","Rhizobium \ncapsici 2","Sphingomonas \npituitosa 2","Fervidobacterium \nriparium","All 10 bacteria")

#####################Load 2019 data#######################

df.CKW<-read.table('July2019CKW.txt', header=F, na.strings="", sep="\t")
names(df.CKW)<-c('pop','bac','id','frd0','pix0','per0','grn0','grnper0','frd1','pix1','per1','grn1','grnper1','notes','algae_lvl')

#Fix the structure
df.CKW$pop<-as.factor(df.CKW$pop)
df.CKW$bac<-as.factor(df.CKW$bac)

# Add in edge (15 plates)
edge3<-rep(edge,15)
df.CKW$edge<-edge3

df.CKW$edge <- as.factor(df.CKW$edge)
df.CKW$algae_lvl<-as.factor(df.CKW$algae_lvl)

plate2<-vector()
# Create vector for plate
for (i in 1:15){
  plate2<-c(plate2, rep(i,24))
}

df.CKW$plate <- plate2
df.CKW$plate <- as.factor(df.CKW$plate)

df.CKW$Grt<-df.CKW$pix1 - df.CKW$pix0

# We want to include algal level as an ordinal variable.
df.CKW$alg.ord<- factor(df.CKW$algae_lvl, order = TRUE, levels = c("None","Low", "Med", "High"))

# Let's break this down by population.
df.C.2019<-subset(df.CKW, df.CKW$pop== "Churchill")
df.K.2019<-subset(df.CKW, df.CKW$pop== "Kelso")
df.W.2019<-subset(df.CKW, df.CKW$pop== "Wellspring ")

# Change factor order of bacteria to reflect their effects on duckweed growth.
#First, let's change the order of bacteria, ranked by effect. 
df.C.2019$bac<- factor(df.C.2019$bac, levels = c("0","7","8","5","6","10","4","9","2","1","3","All"))
# Assign names from sequencing
levels(df.C.2019$bac) <- c("Control","Aeromonas \nsalmonicida 1","Aeromonas \nsalmonicida 2","Microbacterium sp.","Parasediminibacterium \npaludis","Flavibacterium \nsuccinicans 1","Arcicella sp.","Falsiroseomonas \nstagni","Pseudomonas \nprotogens","Flavibacterium \nsuccinicans 2","Ohtaekwangia \nkoreensis","All 10 bacteria")

df.K.2019$bac<- factor(df.K.2019$bac, levels = c("0","8","6","7","3","9","2","5","1","4","10","All"))
levels(df.K.2019$bac) <- c("Control","Pseudomonas \nprotogens","Flavobacterium \nbranchiicola","Pseudomonas \nbaetica","Rhizobium sp.","Pseudacidovorax \nintermedius","Rhizobium \nrosettiformans","Flavobacterium \npanici 1","Flavobacterium \npanici 2","Flavobacterium \npanici 3","Pseudomonas \nsesami","All 10 bacteria")

df.W.2019$bac<- factor(df.W.2019$bac, levels = c("0","8","5","3","2","4","6","9","7","1","10","All"))
levels(df.W.2019$bac) <- c("Control","Rhizobium sp.","Agrobacterium sp.","Rhizobium \nrosettiformans 1","Rhizobium \nrhizophilum","Rhizobium \nrosettiformans 2","Rhizobium \nhelianthi","Sphingomonas \npituitosa","Rhizorhabdus \nwittichii","Rhizobium \nglycinendophyticum","Phenylobacterium \npanacis","All 10 bacteria")
```

SECTION 3: Plant growth models and figures

```{r Duckweed growth}

#Churchill 2019

lmer.grt.C2019<-lmer(pix1 ~ pix0 + bac + alg.ord + (1|edge) + (1|plate), data=df.C.2019)
anova(lmer.grt.C2019)
ranova(lmer.grt.C2019)
summary(lmer.grt.C2019)
plot(lmer.grt.C2019)

#Kelso 2019

lmer.grt.K2019<-lmer(pix1 ~ pix0 + bac + alg.ord + (1|edge) + (1|plate), data=df.K.2019)
anova(lmer.grt.K2019)
ranova(lmer.grt.K2019)
summary(lmer.grt.K2019)
plot(lmer.grt.K2019)

#Wellspring 2019

lmer.grt.W2019<-lmer(pix1 ~ pix0 + bac + alg.ord + (1|edge) + (1|plate), data=df.W.2019)
anova(lmer.grt.W2019)
ranova(lmer.grt.W2019)
summary(lmer.grt.W2019)
plot(lmer.grt.W2019)

#Churchill 2020

lmer.grt.C2020<-lmer(pix1 ~ pix0 + bac + (1|edge) + (1|plate), data=df.C.2020)
anova(lmer.grt.C2020)
ranova(lmer.grt.C2020)
summary(lmer.grt.C2020)
plot(lmer.grt.C2020)

#Wellspring 2020

lmer.grt.W2020<-lmer(pix1 ~ pix0 + bac + (1|edge) + (1|plate), data=df.W.2020)
anova(lmer.grt.W2020)
ranova(lmer.grt.W2020)
summary(lmer.grt.W2020)
plot(lmer.grt.W2020)

##########################################################################################

# Onto figure generation - plotting Log Response Ratios of bacterial effects on plant growth

# Churchill 2019

# Reference for calculating LRR's: Hedges, L. V., Gurevitch, J., & Curtis, P. S. (1999). The meta-analysis of response ratios in experimental ecology. Ecology, 80(4), 1150-1156. Equation 1

melt.C.2019<-melt(df.C.2019, id.vars=c("bac"), measure.vars= "Grt", na.rm = T)
Sum.C.2019<- ddply(melt.C.2019, c("bac","variable"), summarise, mean = mean(value), sd = sd(value), count=n(),  sem = sd(value)/sqrt(length(value)))

lrr.C.2019<-data.frame(matrix(ncol=4, nrow=11))
names(lrr.C.2019)<-c('bac','LRR','var','SD')
lrr.C.2019$bac<-Sum.C.2019$bac[2:12]

for (i in 1:11){
  lrr.C.2019[i,2]<-log(Sum.C.2019[i+1,3]/Sum.C.2019[1,3])
  lrr.C.2019[i,3]<-Sum.C.2019[i+1,4]^2/(Sum.C.2019[i+1,5]*Sum.C.2019[i+1,3]^2) + Sum.C.2019[1,5]^2/(Sum.C.2019[1,6]*Sum.C.2019[1,4]^2)
}
lrr.C.2019$SD<-sqrt(lrr.C.2019$var)
lrr.C.2019$cnt<-Sum.C.2019$count[2:12]
lrr.C.2019$SE<-lrr.C.2019$SD/sqrt(lrr.C.2019$cnt)
lrr.C.2019$CI<-qnorm(0.975)*lrr.C.2019$SE

# Kelso 2019

melt.K.2019<-melt(df.K.2019, id.vars=c("bac"), measure.vars= "Grt", na.rm = T)
Sum.K.2019<- ddply(melt.K.2019, c("bac","variable"), summarise, mean = mean(value), sd = sd(value), count=n(), sem = sd(value)/sqrt(length(value)))

lrr.K.2019<-data.frame(matrix(ncol=4, nrow=11))
names(lrr.K.2019)<-c('bac','LRR','var','SD')
lrr.K.2019$bac<-Sum.K.2019$bac[2:12]

for (i in 1:11){
  lrr.K.2019[i,2]<-log(Sum.K.2019[i+1,3]/Sum.K.2019[1,3])
  lrr.K.2019[i,3]<-Sum.K.2019[i+1,4]^2/(Sum.K.2019[i+1,5]*Sum.K.2019[i+1,3]^2) + Sum.K.2019[1,5]^2/(Sum.K.2019[1,6]*Sum.K.2019[1,4]^2)
}
lrr.K.2019$SD<-sqrt(lrr.K.2019$var)
lrr.K.2019$cnt<-Sum.K.2019$count[2:12]
lrr.K.2019$SE<-lrr.K.2019$SD/sqrt(lrr.K.2019$cnt)
lrr.K.2019$CI<-qnorm(0.975)*lrr.K.2019$SE

# Wellspring 2019

melt.W.2019<-melt(df.W.2019, id.vars=c("bac"), measure.vars= "Grt", na.rm = T)
Sum.W.2019<- ddply(melt.W.2019, c("bac","variable"), summarise, mean = mean(value), sd = sd(value), count=n(), sem = sd(value)/sqrt(length(value)))

lrr.W.2019<-data.frame(matrix(ncol=4, nrow=11))
names(lrr.W.2019)<-c('bac','LRR','var','SD')
lrr.W.2019$bac<-Sum.W.2019$bac[2:12]

for (i in 1:11){
  lrr.W.2019[i,2]<-log(Sum.W.2019[i+1,3]/Sum.W.2019[1,3])
  lrr.W.2019[i,3]<-Sum.W.2019[i+1,4]^2/(Sum.W.2019[i+1,5]*Sum.W.2019[i+1,3]^2) + Sum.W.2019[1,5]^2/(Sum.W.2019[1,6]*Sum.W.2019[1,4]^2)
}
lrr.W.2019$SD<-sqrt(lrr.W.2019$var)
lrr.W.2019$cnt<-Sum.W.2019$count[2:12]
lrr.W.2019$SE<-lrr.W.2019$SD/sqrt(lrr.W.2019$cnt)
lrr.W.2019$CI<-qnorm(0.975)*lrr.W.2019$SE

# Churchill 2020

melt.C.2020<-melt(df.C.2020, id.vars=c("bac"), measure.vars= "Grt", na.rm = T)
Sum.C.2020<- ddply(melt.C.2020, c("bac","variable"), summarise, mean = mean(value), sd = sd(value), count=n(), sem = sd(value)/sqrt(length(value)))

lrr.C.2020<-data.frame(matrix(ncol=4, nrow=11))
names(lrr.C.2020)<-c('bac','LRR','var','SD')
lrr.C.2020$bac<-Sum.C.2020$bac[2:12]

for (i in 1:11){
  lrr.C.2020[i,2]<-log(Sum.C.2020[i+1,3]/Sum.C.2020[1,3])
  lrr.C.2020[i,3]<-Sum.C.2020[i+1,4]^2/(Sum.C.2020[i+1,5]*Sum.C.2020[i+1,3]^2) + Sum.C.2020[1,5]^2/(Sum.C.2020[1,6]*Sum.C.2020[1,4]^2)
}
lrr.C.2020$SD<-sqrt(lrr.C.2020$var)
lrr.C.2020$cnt<-Sum.C.2020$count[2:12]
lrr.C.2020$SE<-lrr.C.2020$SD/sqrt(lrr.C.2020$cnt)
lrr.C.2020$CI<-qnorm(0.975)*lrr.C.2020$SE

#Wellspring
melt.W.2020<-melt(df.W.2020, id.vars=c("bac"), measure.vars= "Grt", na.rm = T)
Sum.W.2020<- ddply(melt.W.2020, c("bac","variable"), summarise, mean = mean(value), sd = sd(value), count=n(), sem = sd(value)/sqrt(length(value)))

lrr.W.2020<-data.frame(matrix(ncol=4, nrow=11))
names(lrr.W.2020)<-c('bac','LRR','var','SD')
lrr.W.2020$bac<-Sum.W.2020$bac[2:12]

for (i in 1:11){
  lrr.W.2020[i,2]<-log(Sum.W.2020[i+1,3]/Sum.W.2020[1,3])
  lrr.W.2020[i,3]<-Sum.W.2020[i+1,4]^2/(Sum.W.2020[i+1,5]*Sum.W.2020[i+1,3]^2) + Sum.W.2020[1,5]^2/(Sum.W.2020[1,6]*Sum.W.2020[1,4]^2)
}
lrr.W.2020$SD<-sqrt(lrr.W.2020$var)
lrr.W.2020$cnt<-Sum.W.2020$count[2:12]
lrr.W.2020$SE<-lrr.W.2020$SD/sqrt(lrr.W.2020$cnt)
lrr.W.2020$CI<-qnorm(0.975)*lrr.W.2020$SE

#OK, let's get to plotting!

pred.C.2019<-mean(lrr.C.2019$LRR[1:10])

plot1.C1 <- ggplot(lrr.C.2019,aes(y=LRR,x=bac,colour=bac))+geom_errorbar(aes(ymin=LRR-CI,ymax=LRR+CI),width=0.5)+geom_point(size=3)
plot1.C1 <- plot1.C1 + geom_hline(yintercept=pred.C.2019, linetype="dashed", color = "blue3",size=1)
plot1.C1 <- plot1.C1 + theme_classic() + ggtitle("Churchill, 2019") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot1.C1 <- plot1.C1 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot1.C1 <- plot1.C1 + theme(legend.position = "none")
plot1.C1 <- plot1.C1 + labs(x= element_blank()) 
plot1.C1 <- plot1.C1 + labs(y= element_blank())
plot1.C1 <- plot1.C1 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))
plot1.C1 <- plot1.C1 + geom_hline(yintercept=0, linetype="dashed", color = "red3",size=1)

#Kelso 2019

pred.K.2019<-mean(lrr.K.2019$LRR[1:10])

plot1.K1 <- ggplot(lrr.K.2019,aes(y=LRR,x=bac,colour=bac))+geom_errorbar(aes(ymin=LRR-CI,ymax=LRR+CI),width=0.5)+geom_point(size=3)
plot1.K1 <- plot1.K1 + geom_hline(yintercept=pred.K.2019, linetype="dashed", color = "blue3",size=1)
plot1.K1 <- plot1.K1 + theme_classic() + ggtitle("Kelso, 2019") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot1.K1 <- plot1.K1 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot1.K1 <- plot1.K1 + theme(legend.position = "none")
plot1.K1 <- plot1.K1 + labs(x= element_blank()) 
plot1.K1 <- plot1.K1 + labs(y= element_blank())
plot1.K1 <- plot1.K1 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))
plot1.K1 <- plot1.K1 + geom_hline(yintercept=0, linetype="dashed", color = "red3",size=1)

#Wellspring 2019

pred.W.2019<-mean(lrr.W.2019$LRR[1:10])

plot1.W1 <- ggplot(lrr.W.2019,aes(y=LRR,x=bac,colour=bac))+geom_errorbar(aes(ymin=LRR-CI,ymax=LRR+CI),width=0.5)+geom_point(size=3)
plot1.W1 <- plot1.W1 + geom_hline(yintercept=pred.W.2019, linetype="dashed", color = "blue3",size=1)
plot1.W1 <- plot1.W1 + theme_classic() + ggtitle("Wellspring, 2019") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot1.W1 <- plot1.W1 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot1.W1 <- plot1.W1 + theme(legend.position = "none")
plot1.W1 <- plot1.W1 + labs(x= element_blank()) 
plot1.W1 <- plot1.W1 + labs(y= element_blank())
plot1.W1 <- plot1.W1 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))
plot1.W1 <- plot1.W1 + geom_hline(yintercept=0, linetype="dashed", color = "red3",size=1)

# Churchill 2020

pred.C.2020<-mean(lrr.C.2020$LRR[1:10])

plot1.C2 <- ggplot(lrr.C.2020,aes(y=LRR,x=bac,colour=bac))+geom_errorbar(aes(ymin=LRR-CI,ymax=LRR+CI),width=0.5)+geom_point(size=3)
plot1.C2 <- plot1.C2 + geom_hline(yintercept=pred.C.2020, linetype="dashed", color = "blue3",size=1)
plot1.C2 <- plot1.C2 + theme_classic() + ggtitle("Churchill, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot1.C2 <- plot1.C2 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot1.C2 <- plot1.C2 + theme(legend.position = "none")
plot1.C2 <- plot1.C2 + labs(x= element_blank()) 
plot1.C2 <- plot1.C2 + labs(y= element_blank())
plot1.C2 <- plot1.C2 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))
plot1.C2 <- plot1.C2 + geom_hline(yintercept=0, linetype="dashed", color = "red3",size=1)

# Wellspring 2020

pred.W.2020<-mean(lrr.W.2020$LRR[1:10])

plot1.W2 <- ggplot(lrr.W.2020,aes(y=LRR,x=bac,colour=bac))+geom_errorbar(aes(ymin=LRR-CI,ymax=LRR+CI),width=0.5)+geom_point(size=3)
plot1.W2 <- plot1.W2 + geom_hline(yintercept=pred.W.2020, linetype="dashed", color = "blue3",size=1)
plot1.W2 <- plot1.W2 + theme_classic() + ggtitle("Wellspring, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot1.W2 <- plot1.W2 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot1.W2 <- plot1.W2 + theme(legend.position = "none")
plot1.W2 <- plot1.W2 + labs(x= element_blank()) 
plot1.W2 <- plot1.W2 + labs(y= element_blank())
plot1.W2 <- plot1.W2 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))
plot1.W2 <- plot1.W2 + geom_hline(yintercept=0, linetype="dashed", color = "red3",size=1)

#Legend plot
#Create dead column for individual bacteria
lrr.C.2019$legend.bac<-c(rep('Individual bacteria',10),'All 10 bacteria')
lrr.C.2019$legend.bac<-as.factor(lrr.C.2019$legend.bac)
factor(lrr.C.2019$legend.bac, levels = c("Individual bacteria","All 10 bacteria"))

lrr.C.2019$legend.line<-c(rep('No effect of inoculation',6),rep('Mean effect of individual bacteria',5))
lrr.C.2019$legend.line<-as.factor(lrr.C.2019$legend.line)

leg.plot <- ggplot(lrr.C.2019, aes(x = LRR, y = var, colour = legend.bac)) + geom_point(size=3)
leg.plot <- leg.plot + scale_colour_manual(name="Bacterial inocula",values=c("blue3","#000000"))
leg.plot <- leg.plot + theme_classic()
leg.plot <- leg.plot + theme(
  legend.title=element_text(size=14, face='bold'),
  legend.text=element_text(size=12, face='bold')
)

leg.1 <- get_legend(leg.plot)  

leg.plot.2 <- ggplot(lrr.C.2019, aes(x = LRR, y = var, colour = legend.line)) + geom_point(size=3) + geom_line(linetype="dashed",size=1)
leg.plot.2 <- leg.plot.2 + scale_colour_manual(name="Line",values=c("blue3","red3"))
leg.plot.2 <- leg.plot.2 + theme_classic() 
leg.plot.2 <- leg.plot.2 + theme(
  legend.title=element_text(size=14, face='bold'),
  legend.text=element_text(size=12, face='bold')
)

leg.2 <- get_legend(leg.plot.2)  

plot.leg<-plot_grid(leg.1, leg.2, ncol=1,nrow=2, align='v')

# Generate figure 1

x.grob_bac <- textGrob(expression(bold("Bacterial strain")), gp=gpar(fontsize=12))
y.grob_lrrdw <- textGrob(expression(bold("                     Duckweed growth (LRR)")), gp=gpar(fontsize=12), rot=90)

# Re-scale y axes
plot1.C1 <- plot1.C1 + ylim(-2.4,0.85)
plot1.K1 <- plot1.K1 + ylim(-2.4,0.85)
plot1.W1 <- plot1.W1 + ylim(-2.4,0.85)

plot1.C2 <- plot1.C2 + ylim(-0.2,0.4)
plot1.W2 <- plot1.W2 + ylim(-0.2,0.4)

plot1.2019<-plot_grid(plot1.C1, plot1.K1, plot1.W1, ncol=3,nrow=1, align='h', labels=c('A','B','C'))
plot1.2020<-plot_grid(plot1.C2, plot1.W2, plot.leg, ncol=3,nrow=1, align='h', labels=c('D','E'))

plot1<-plot_grid(plot1.2019,plot1.2020, ncol=1, nrow=2, align='v')
grid.arrange(arrangeGrob(plot1, bottom = x.grob_bac, left = y.grob_lrrdw))

# PDF , 10 x 12.5 " works well
```
SECTION 3: Microbial growth models and figures

```{r Microbial growth models}
#Churchill 2020

# Model 1 : we will exclude control plants, and use All10_pltN as our reference treatment.
df.C.2020$bac2<-df.C.2020$bac
df.C.2020 <- within(df.C.2020, bac2 <- relevel(bac2, ref = 12))

lmer.abs.C<-lmer(logabs~bac2*plt + (1|edge) + (1|plate), data=df.C.2020)
anova(lmer.abs.C)
ranova(lmer.abs.C)
plot(lmer.abs.C)
summary(lmer.abs.C)

#Model 2 : we will exclude wells without plants to estimate variation in bacterial cell density when co-cultured with plants.
df.C.2020.plt<-subset(df.C.2020,df.C.2020$plt=="Y")
lmer.abs.C.2<-lmer(logabs~bac2 + (1|edge) + (1|plate), data=df.C.2020.plt)
summary(lmer.abs.C.2)

#Wellspring 2020

df.W.2020$bac2<-df.W.2020$bac
df.W.2020 <- within(df.W.2020, bac2 <- relevel(bac2, ref = 12))

lmer.abs.W<-lmer(logabs~bac2*plt + (1|edge) + (1|plate), data=df.W.2020)
anova(lmer.abs.W, type=3)
ranova(lmer.abs.W)
plot(lmer.abs.W)
summary(lmer.abs.W)

df.W.2020.plt<-subset(df.W.2020,df.W.2020$plt=="Y")
lmer.abs.W.2<-lmer(logabs~bac2 + (1|edge) + (1|plate), data=df.W.2020.plt)
summary(lmer.abs.W.2)

# Generate Figure 2

melt.C.abs<-melt(df.C.2020, id.vars=c("bac","plt"), measure.vars= "abs", na.rm = T)
Sum.C.abs<- ddply(melt.C.abs, c("bac","plt","variable"), summarise, mean = mean(value), sd = sd(value), count=n(), sem = sd(value)/sqrt(length(value)))

# Re-order by bacterial population size

Sum.C.abs$bac <- factor(Sum.C.abs$bac, levels = c("Control","Microbacterium \noxydans","Bosea \nmassiliensis","Flavobacterium \nsuccinicans 1","Falsiroseomonas \nstagni","Ohtaekwangia \nkoreensis","Flavobacterium \nsuccinicans 2","Aeromonas \nsalmonicida","Arcicella sp.","Parasediminibacterium \npaludis","Pseudomonas \nprotogens","All 10 bacteria"))
Sum.C.abs$CI<-qnorm(0.975)*Sum.C.abs$sd/sqrt(Sum.C.abs$count)

Sum.C.plt<-subset(Sum.C.abs, Sum.C.abs$plt=="Y")
Sum.C.plt<-Sum.C.plt[2:12,]
Sum.C.plt$CI<-qnorm(0.975)*Sum.C.plt$sd/sqrt(Sum.C.plt$count)

Sum.C.bac<-subset(Sum.C.abs, Sum.C.abs$plt=="N")
Sum.C.bac$CI<-qnorm(0.975)*Sum.C.bac$sd/sqrt(Sum.C.bac$count)

pred.C.plt<-mean(Sum.C.plt$mean[1:10])
pred.C.bac<-mean(Sum.C.bac$mean[1:10])

plot2.C1 <- ggplot(Sum.C.bac,aes(y=mean,x=bac,colour=bac))+geom_errorbar(aes(ymin=mean-CI,ymax=mean+CI),width=0.5)+geom_point(size=3)
plot2.C1 <- plot2.C1 + geom_hline(yintercept=pred.C.bac, linetype="dashed", color = "blue3",size=1)
plot2.C1 <- plot2.C1 + theme_classic() + ggtitle("Churchill, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot2.C1 <- plot2.C1 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot2.C1 <- plot2.C1 + theme(legend.position = "none")
plot2.C1 <- plot2.C1 + labs(x= element_blank()) 
plot2.C1 <- plot2.C1 + labs(y= element_blank())
plot2.C1 <- plot2.C1 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))

plot2.C2 <- ggplot(Sum.C.plt,aes(y=mean,x=bac,colour=bac))+geom_errorbar(aes(ymin=mean-CI,ymax=mean+CI),width=0.5)+geom_point(size=3)
plot2.C2 <- plot2.C2 + geom_hline(yintercept=pred.C.plt, linetype="dashed", color = "blue3",size=1)
plot2.C2 <- plot2.C2 + theme_classic() + ggtitle("Churchill, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot2.C2 <- plot2.C2 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot2.C2 <- plot2.C2 + theme(legend.position = "none")
plot2.C2 <- plot2.C2 + labs(x= element_blank()) 
plot2.C2 <- plot2.C2 + labs(y= element_blank())
plot2.C2 <- plot2.C2 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))

#Wellspring

melt.W.abs<-melt(df.W.2020, id.vars=c("bac","plt"), measure.vars= "abs", na.rm = T)
Sum.W.abs<- ddply(melt.W.abs, c("bac","plt","variable"), summarise,
                mean = mean(value), sd = sd(value), count=n(),
                sem = sd(value)/sqrt(length(value)))

Sum.W.abs$bac <- factor(Sum.W.abs$bac, levels = c("Control","Flaviflagellibacter \ndeserti","Rhizorhabdus \nwittichii 2","Rhizorhabdus \nwittichii 1","Rhizobium \ncapsici 2","Rhizobium \ncapsici 1","Sphingomonas \npituitosa 2","Sphingomonas \npituitosa 1","Fervidobacterium \nriparium","Rhizobium \nrosettiformans","Pseudomonas \nprotogens","All 10 bacteria"))
Sum.W.abs$CI<-qnorm(0.975)*Sum.W.abs$sd/sqrt(Sum.W.abs$count)

Sum.W.plt<-subset(Sum.W.abs, Sum.W.abs$plt=="Y")
Sum.W.plt<-Sum.W.plt[2:12,]
Sum.W.plt$CI<-qnorm(0.975)*Sum.W.plt$sd/sqrt(Sum.W.plt$count)

Sum.W.bac<-subset(Sum.W.abs, Sum.W.abs$plt=="N")
Sum.W.bac$CI<-qnorm(0.975)*Sum.W.bac$sd/sqrt(Sum.W.bac$count)

pred.W.plt<-mean(Sum.W.plt$mean[1:10])
pred.W.bac<-mean(Sum.W.bac$mean[1:10])

plot2.W1 <- ggplot(Sum.W.bac,aes(y=mean,x=bac,colour=bac))+geom_errorbar(aes(ymin=mean-CI,ymax=mean+CI),width=0.5)+geom_point(size=3)
plot2.W1 <- plot2.W1 + geom_hline(yintercept=pred.W.bac, linetype="dashed", color = "blue3",size=1)
plot2.W1 <- plot2.W1 + theme_classic() + ggtitle("Wellspring, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot2.W1 <- plot2.W1 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot2.W1 <- plot2.W1 + theme(legend.position = "none")
plot2.W1 <- plot2.W1 + labs(x= element_blank()) 
plot2.W1 <- plot2.W1 + labs(y= element_blank())
plot2.W1 <- plot2.W1 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))

plot2.W2 <- ggplot(Sum.W.plt,aes(y=mean,x=bac,colour=bac))+geom_errorbar(aes(ymin=mean-CI,ymax=mean+CI),width=0.5)+geom_point(size=3)
plot2.W2 <- plot2.W2 + geom_hline(yintercept=pred.W.plt, linetype="dashed", color = "blue3",size=1)
plot2.W2 <- plot2.W2 + theme_classic() + ggtitle("Wellspring, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot2.W2 <- plot2.W2 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot2.W2 <- plot2.W2 + theme(legend.position = "none")
plot2.W2 <- plot2.W2 + labs(x= element_blank()) 
plot2.W2 <- plot2.W2 + labs(y= element_blank())
plot2.W2 <- plot2.W2 + theme(axis.text.x = element_text(face="italic",angle = 90,vjust=0.5,hjust=1))

# Re-scale y axes
plot2.C1 <- plot2.C1 + ylim(-500,15000)
plot2.W1 <- plot2.W1 + ylim(-500,15000)

plot2.C2 <- plot2.C2 + ylim(0,12000)
plot2.W2 <- plot2.W2 + ylim(0,12000)

#OK, now we need to combine them both and make a reaction norm plot.

Sum.C.abs2 <- Sum.C.abs[2:23,]

plot2.C3 <- ggplot(Sum.C.abs2, aes(x = plt, y = mean, colour=bac)) +  stat_summary(aes(group = bac), fun = mean, geom = "path") +geom_point(size=3)
plot2.C3 <- plot2.C3 + theme_classic() + ggtitle("Churchill, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot2.C3 <- plot2.C3 + labs(x= element_blank())
plot2.C3 <- plot2.C3 + labs(y= element_blank())
plot2.C3 <- plot2.C3 + theme(axis.title = element_text(face="bold", size=12))
plot2.C3 <- plot2.C3 + scale_x_discrete(labels=c("N" = "No duckweed", "Y" = "Duckweed"))
plot2.C3 <- plot2.C3 + theme(axis.text.x = element_text(face="bold",size = 12, colour="black"))
plot2.C3 <- plot2.C3 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot2.C3 <- plot2.C3 + theme(legend.position = "none")

Sum.W.abs2 <- Sum.W.abs[2:23,]

plot2.W3 <- ggplot(Sum.W.abs2, aes(x = plt, y = mean, colour=bac)) +  stat_summary(aes(group = bac), fun = mean, geom = "path") +geom_point(size=3)
plot2.W3 <- plot2.W3 + theme_classic() + ggtitle("Wellspring, 2020") + theme(plot.title = element_text(size=14, face='bold', hjust = 0.5))
plot2.W3 <- plot2.W3 + labs(x= element_blank())
plot2.W3 <- plot2.W3 + labs(y= element_blank())
plot2.W3 <- plot2.W3 + theme(axis.title = element_text(face="bold", size=12))
plot2.W3 <- plot2.W3 + scale_x_discrete(labels=c("N" = "No duckweed", "Y" = "Duckweed"))
plot2.W3 <- plot2.W3 + theme(axis.text.x = element_text(face="bold",size = 12, colour="black"))
plot2.W3 <- plot2.W3 + scale_colour_manual(values=c("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000","blue3"))
plot2.W3 <- plot2.W3 + theme(legend.position = "none")

plot2.bac1<-plot_grid(plot2.C1, plot2.C2, plot2.C3, ncol=3,nrow=1, align='h', labels = c('A','B','C'))
plot2.bac2<-plot_grid(plot2.W1, plot2.W2, plot2.W3, ncol=3,nrow=1, align='h', labels = c('D','E','F'))

plot2.1<-plot_grid(plot2.bac1,plot2.bac2, nrow = 2, ncol=1, align='v')

y.grob_abs <- textGrob(expression(bold("                       Microbial density (cells/µL)")), gp=gpar(fontsize=12), rot=90)

x.grob_bac2 <- textGrob(expression(bold("Bacteria                                                                     ")), gp=gpar(fontsize=12))

x.grob.plt <- textGrob(expression(bold("No plants                                                                      Plants                                                                           ")), gp=gpar(fontsize=12))

grid.arrange(arrangeGrob(plot2.1, left = y.grob_abs, bottom = x.grob_bac2, top=x.grob.plt))

#Let's arrange it the other way too.

plot2.C1b <- plot2.C1 + labs(y= "No plants") 
plot2.C1b <- plot2.C1b + theme(axis.title = element_text(size=12, face='bold'))

plot2.C2b <- plot2.C2 + labs(y= "Plants") 
plot2.C2b <- plot2.C2b + theme(axis.title = element_text(size=12, face='bold'))

plot2.bac1b<-plot_grid(plot2.C1b, plot2.W1, plot2.C3, ncol=3,nrow=1, align='h', labels = c('A','B','E'))
plot2.bac2b<-plot_grid(plot2.C2b, plot2.W2, plot2.W3, ncol=3,nrow=1, align='h', labels = c('C','D','F'))

plot2.2<-plot_grid(plot2.bac1b,plot2.bac2b, nrow = 2, ncol=1, align='v')

grid.arrange(arrangeGrob(plot2.2, left = y.grob_abs, bottom = x.grob_bac2))

```

